// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDepoe9a51DbQxQOVawVng-ZeIOKNFfDps',
    appId: '1:143560992973:web:8815ea9acc74fe7d07a184',
    messagingSenderId: '143560992973',
    projectId: 'chat-app-real100',
    authDomain: 'chat-app-real100.firebaseapp.com',
    storageBucket: 'chat-app-real100.firebasestorage.app',
    measurementId: 'G-GK6DZM3QW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo4Fz1HMPTycPYkXWV9nUBb-VPvgQ461w',
    appId: '1:143560992973:android:d0f454df8839381f07a184',
    messagingSenderId: '143560992973',
    projectId: 'chat-app-real100',
    storageBucket: 'chat-app-real100.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw4tCRrF7ZE_1Mw58KJjuBdMkEQC7Xpms',
    appId: '1:143560992973:ios:466b705f77a07dd607a184',
    messagingSenderId: '143560992973',
    projectId: 'chat-app-real100',
    storageBucket: 'chat-app-real100.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw4tCRrF7ZE_1Mw58KJjuBdMkEQC7Xpms',
    appId: '1:143560992973:ios:466b705f77a07dd607a184',
    messagingSenderId: '143560992973',
    projectId: 'chat-app-real100',
    storageBucket: 'chat-app-real100.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDepoe9a51DbQxQOVawVng-ZeIOKNFfDps',
    appId: '1:143560992973:web:e040b97d0a77dd2107a184',
    messagingSenderId: '143560992973',
    projectId: 'chat-app-real100',
    authDomain: 'chat-app-real100.firebaseapp.com',
    storageBucket: 'chat-app-real100.firebasestorage.app',
    measurementId: 'G-GCDHF9Y6WP',
  );
}
